# Generated by Django 4.0.2 on 2022-08-31 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
