# Generated by Django 4.0.2 on 2022-09-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_usersettings_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='score_tier',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
