# Generated by Django 4.0.2 on 2023-01-13 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_task_score_tier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='group',
        ),
    ]
